### ISSUE TITLE
502 bad gateway on web Server 

### ISSUE THREAD

**Issue by foollefille** [maxking/docker-mailman#103]
Hello All , 

Im facing an issue while displaying the web interface "I got 502 Bad Gateway" , it worked before after changing the config of nginx by adding proxy_pass . But now with the new image the same problem .
Any help would be appreciated .
Here it is my configurations : 

**Docker-compose.yaml
```yaml
version: '2'

services:
  mailman-core:
    image: maxking/mailman-core:0.1
    container_name: mailman-core
    hostname: mailman-core
    volumes:
    - /opt/mailman/core:/opt/mailman/
    links:
    - database:database
    depends_on:
    - database
    environment:
    - DATABASE_URL=postgres://mailman:mailmanpass@192.168.250.4/mailmandb
    - DATABASE_TYPE=postgres
    - DATABASE_CLASS=mailman.database.postgresql.PostgreSQLDatabase
    - HYPERKITTY_API_KEY=someapikey
    networks:
      mailman:
        ipv4_address: 192.168.250.2

  mailman-web:
    image: maxking/mailman-web:0.1
    container_name: mailman-web
    hostname: mailman-web
    depends_on:
    - database
    links:
    - mailman-core:mailman-core
    - database:database
    volumes:
    - /opt/mailman/web:/opt/mailman-web-data
    environment:
    - DATABASE_TYPE=postgres
    - DATABASE_URL=postgres://mailman:mailmanpass@192.168.250.4/mailmandb
    - HYPERKITTY_API_KEY=someapikey
    networks:
      mailman:
        ipv4_address: 192.168.250.3

  database:
    environment:
      POSTGRES_DB: mailmandb
      POSTGRES_USER: mailman
      POSTGRES_PASSWORD: mailmanpass
    restart: always
    image: postgres:9.6
    volumes:
    - /opt/mailman/database:/var/lib/postgresql/data
    networks:
      mailman:
        ipv4_address: 192.168.250.4

networks:
   mailman:
     driver: bridge
     ipam:
       driver: default
       config:
       -
         subnet: 192.168.250.0/24
``` 

 ** mailman.cfg 
```
[mta]
incoming: mailman.mta.postfix.LMTP
outgoing: mailman.mta.deliver.deliver
lmtp_host: 192.168.250.2
lmtp_port: 8024
smtp_host: 192.168.250.1
smtp_port: 25
configuration: /etc/postfix-mailman.cfg

# [archiver.mhonarc]
# enable: yes

# [archiver.mail_archive]
# enable: yes

# [archiver.prototype]
# enable: yes

[runner.retry]
sleep_time: 10s

[shell]
use_ipython: yes

[webservice]
hostname: mailman-core

[archiver.hyperkitty]
class: mailman_hyperkitty.Archiver
enable: yes
configuration: /opt/mailman/mailman-hyperkitty.cfg

[database]
class: mailman.database.postgresql.PostgreSQLDatabase
url: postgres://mailman:mailmanpass@192.168.250.4/mailmandb
```

**nginx.conf 
```
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    include /etc/nginx/conf.d/*.conf;

    server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }

# Settings for a TLS enabled server.
#
    server {
        listen       443 ssl default_server;
        listen       [::]:443 ssl default_server;
        server_name  mailman.esi-group.com;

        location /static/ {
             alias /opt/mailman/web/static/;
        }
         ssl_certificate /etc/ssl/ca.crt;
         ssl_certificate_key /etc/ssl/ca.key;
	location / {
                # First attempt to serve request as file, then
                 proxy_pass http://192.168.250.3:8000;
		         uwsgi_read_timeout 300;
			     proxy_set_header Host $host;
			     proxy_set_header X-Forwarded-For $remote_addr; 
        }
}
}

```
**settings.py
```
ALLOWED_HOSTS = [
    "localhost",  # Archiving API from Mailman, keep it.
    "mailman.esi-group.com",
    # Add here all production URLs you may have.
    "mailman-web",
    "127.0.0.1",
    "172.16.12.115",
    "192.168.250.1",
    "172.16.12.115",
    "192.168.250.3:8000",
    "192.168.250.3",
    os.environ.get('SERVE_FROM_DOMAIN'),
]
```
