### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by aralon** [maxking/docker-mailman#234]
After following this tutorial: https://xiaoxing.us/2018/01/01/deploy-mailman-3-on-aws-using-docker/, I end up with a 502 bad gateway error when accessing Mailman. Below you can find all of the log file contents and relevant setting files.

Other info:
- Running mailman on Ubuntu 16.04
- Docker 18.03.0-ce, build 0520e24
- docker-compose version 1.21.0, build 5920eb0
- nginx/1.10.3 (Ubuntu)

**mailmanweb.log**
`empty`

**uwsgi-error.log**
```
uwsgi_proto_http_parser() -> client closed connection                                                  
Sat Apr 14 19:53:50 2018 - [uwsgi-cron] running "./manage.py runjobs minutely" (pid 301)               
[uwsgi-cron] command "./manage.py runjobs minutely" running with pid 301 exited after 3 second(s)      
Sat Apr 14 19:54:50 2018 - [uwsgi-cron] running "./manage.py runjobs minutely" (pid 309)               
[uwsgi-cron] command "./manage.py runjobs minutely" running with pid 309 exited after 3 second(s)      
Sat Apr 14 19:55:50 2018 - [uwsgi-cron] running "./manage.py runjobs minutely" (pid 317)               
[uwsgi-cron] command "./manage.py runjobs minutely" running with pid 317 exited after 3 second(s)      
Sat Apr 14 19:56:50 2018 - [uwsgi-cron] running "./manage.py runjobs minutely" (pid 325)               
[uwsgi-cron] command "./manage.py runjobs minutely" running with pid 325 exited after 3 second(s)      
Sat Apr 14 19:57:50 2018 - [uwsgi-cron] running "./manage.py runjobs minutely" (pid 333)               
[uwsgi-cron] command "./manage.py runjobs minutely" running with pid 333 exited after 3 second(s)      
Sat Apr 14 19:58:50 2018 - [uwsgi-cron] running "./manage.py runjobs minutely" (pid 341)               
[uwsgi-cron] command "./manage.py runjobs minutely" running with pid 341 exited after 3 second(s)      
Sat Apr 14 19:59:50 2018 - [uwsgi-cron] running "./manage.py runjobs minutely" (pid 349)               
[uwsgi-cron] command "./manage.py runjobs minutely" running with pid 349 exited after 3 second(s)      
Sat Apr 14 20:00:00 2018 - [uwsgi-cron] running "./manage.py runjobs quarter_hourly" (pid 357)         
Sat Apr 14 20:00:00 2018 - [uwsgi-cron] running "./manage.py runjobs hourly" (pid 358)                 
[uwsgi-cron] command "./manage.py runjobs quarter_hourly" running with pid 357 exited after 5 second(s)
[uwsgi-cron] command "./manage.py runjobs hourly" running with pid 358 exited after 5 second(s)        
```

**uwsgi.log**
```
[pid: 37|app: 0|req: 1/1] 172.19.199.1 () {24 vars in 291 bytes} [Sat Apr 14 18:40:16 2018] GET /postorius/lists/ => generated 3681 bytes in 4782 msecs (HTTP/1.1 200) 5 headers in 163 bytes (1 switches on core 0)
[pid: 37|app: 0|req: 1/1] 172.19.199.1 () {24 vars in 291 bytes} [Sat Apr 14 18:59:00 2018] GET /postorius/lists/ => generated 3681 bytes in 4069 msecs (HTTP/1.1 200) 5 headers in 163 bytes (1 switches on core 0)
[pid: 37|app: 0|req: 1/1] 172.19.199.1 () {24 vars in 291 bytes} [Sat Apr 14 19:25:08 2018] GET /postorius/lists/ => generated 3681 bytes in 1829 msecs (HTTP/1.1 200) 5 headers in 163 bytes (1 switches on core 0)
```

**nginx error.log**
```
2018/04/14 19:55:14 [error] 12568#12568: *110 upstream prematurely closed connection while reading response header from upstream, client: 212.92.123.5, server: lists.wouterbles.nl, request: "GET / HTTP/1.1", upstream: "uwsgi://172.19.199.3:8000", host: "lists.wouterbles.nl"
2018/04/14 19:55:18 [error] 12568#12568: *112 upstream prematurely closed connection while reading response header from upstream, client: 212.92.123.5, server: lists.wouterbles.nl, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.19.199.3:8000", host: "lists.wouterbles.nl"
```

**nginx access.log**
```
212.92.123.5 - - [14/Apr/2018:19:52:56 +0000] "GET / HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299"
212.92.123.5 - - [14/Apr/2018:19:53:03 +0000] "GET / HTTP/1.1" 502 584 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299"
212.92.123.5 - - [14/Apr/2018:19:53:08 +0000] "GET /favicon.ico HTTP/1.1" 502 584 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299"
212.92.123.5 - - [14/Apr/2018:19:55:14 +0000] "GET / HTTP/1.1" 502 584 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299"
212.92.123.5 - - [14/Apr/2018:19:55:18 +0000] "GET /favicon.ico HTTP/1.1" 502 584 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299"
```

**nginx config**
```
server {                                 
                                         
   listen 80 default_server;             
   listen [::]:80 default_server;        
                                         
   server_name lists.wouterbles.nl;      
   location /static/ {                   
        alias /opt/mailman/web/static/;  
   }                                     
                                         
   location / {                          
           include uwsgi_params;         
           uwsgi_pass 172.19.199.3:8000; 
           uwsgi_read_timeout 300;       
   }                                     
                                         
}  
```

**docker-composer.yaml**
```
version: '2'

services:
  mailman-core:
    image: maxking/mailman-core:0.1
    container_name: mailman-core
    hostname: mailman-core
    volumes:
    - /opt/mailman/core:/opt/mailman/
    stop_grace_period: 30s
    links:
    - database:database
    depends_on:
    - database
    environment:
    - DATABASE_URL=postgres://mailman:mailmanpass@database/mailmandb
    - DATABASE_TYPE=postgres
    - DATABASE_CLASS=mailman.database.postgresql.PostgreSQLDatabase
    - HYPERKITTY_API_KEY=CENSORED
    networks:
      mailman:
        ipv4_address: 172.19.199.2

  mailman-web:
    image: maxking/mailman-web:0.1
    container_name: mailman-web
    hostname: mailman-web
    depends_on:
    - database
    links:
    - mailman-core:mailman-core
    - database:database
    volumes:
    - /opt/mailman/web:/opt/mailman-web-data
    environment:
    - DATABASE_TYPE=postgres
    - DATABASE_URL=postgres://mailman:mailmanpass@database/mailmandb
    - HYPERKITTY_API_KEY=CENSORED
    - SECRET_KEY=CENSORED
    - SERVE_FROM_DOMAIN=lists.wouterbles.nl
    - MAILMAN_ADMIN_USER=lists
    - MAILMAN_ADMIN_EMAIL=whbles@gmail.com
    networks:
      mailman:
        ipv4_address: 172.19.199.3
  database:
    environment:
      POSTGRES_DB: mailmandb
      POSTGRES_USER: mailman
      POSTGRES_PASSWORD: mailmanpass
    restart: always
    image: postgres:9.6-alpine
    volumes:
    - /opt/mailman/database:/var/lib/postgresql/data
    networks:
      mailman:
        ipv4_address: 172.19.199.4

networks:
   mailman:
     driver: bridge
     ipam:
       driver: default
       config:
       -
         subnet: 172.19.199.0/24
```

**settings_local.py**
```
USE_SSL = False
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = '172.19.199.1'
EMAIL_PORT = 25
DEFAULT_FROM_EMAIL = "admin@lists.wouterbles.nl"
SERVER_EMAIL = "admin@lists.wouterbles.nl"
```

**mailman-extra.cfg**
```
[mta]
incoming: mailman.mta.postfix.LMTP
outgoing: mailman.mta.deliver.deliver
lmtp_host: 172.19.199.2
lmtp_port: 8024
smtp_host: 172.19.199.1
smtp_port: 25
configuration: /etc/postfix-mailman.cfg
```

Also, when running `curl http://172.19.199.3:8000/postorius/lists/` on my server I do get the expected HTML page returned.
