### ISSUE TITLE
Gateway timeout when trying to log in

### ISSUE THREAD

**Issue by Zahlii** [maxking/docker-mailman#271]
Hi everyone, 

I am trying to integrate mailman within my docker-compose environment. I can see the mailman & hyperkitty UI without problems, the database access from mailman is working. However, when I try to log into mailman, I get a gateway timeout:

```
mailman-web_1   | [uWSGI] getting INI configuration from /opt/mailman-web/uwsgi.ini
mailman-web_1   | [uwsgi-static] added mapping for /static => /opt/mailman-web-data/static
mail            | Oct 20 19:50:27 mail postfix/master[1819]: daemon started -- version 3.1.8, configuration /etc/postfix
proxy_1         | 2018/10/20 19:53:27 [error] 8#8: *22 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.24.0.1, server: lists.local, request: "POST /accounts/login/ HTTP/1.1", upstream: "uwsgi://172.24.0.11:8080", host: "lists.local", referrer: "http://lists.local/accounts/login/?next=/postorius/lists/"
```

However it is not a database problem - If I try to register as an existing user, I get the message "email already in use" which means mailman is able to query the database. Also IF I TRY TO LOG IN WITH WRONG CREDENTIALS, I don't get the timeout.

I have a reverse proxy running in front of mailman:

```
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Proxy "";

gzip on;
gzip_proxied any;
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

server {
    server_name lists.local;
    listen 80;
    listen 443 ssl;

    location / {
        uwsgi_pass mailman-web:8080;
        include uwsgi_params;
    }
}
```

Docker-compose file content:

```
mailman-core:
    image: maxking/mailman-core:0.2
    volumes:
      - ./data/mailman/var:/opt/mailman/var
      - ./data/mailman/web:/opt/mailman/web
    stop_grace_period: 30s
    links:
      - db
      - mail
    environment:
      - DATABASE_URL=mysql://mailman:${MAILMAN_PASSWORD}@db/mailman?charset=utf8&use_unicode=1
      - DATABASE_TYPE=mysql
      - DATABASE_CLASS=mailman.database.mysql.MySQLDatabase
      - HYPERKITTY_API_KEY=${HYPERKITTY_SHARED_SECRET}
  mailman-web:
    image: maxking/mailman-web:0.2
    links:
      - mailman-core
      - db
    volumes:
      - ./data/mailman/web:/opt/mailman-web-data
    environment:
      - DATABASE_URL=mysql://mailman:${MAILMAN_PASSWORD}@db/mailman?charset=utf8&use_unicode=1
      - DATABASE_TYPE=mysql
      - DATABASE_CLASS=mailman.database.mysql.MySQLDatabase
      - HYPERKITTY_API_KEY=${HYPERKITTY_SHARED_SECRET}
      - SECRET_KEY=${MAILMAN_SECRET}
      - DYLD_LIBRARY_PATH=/usr/local/mysql/lib/
      - SERVE_FROM_DOMAIN=lists.local # local domain
      - UWSGI_STATIC_MAP=/static=/opt/mailman-web-data/static
```
