### ISSUE TITLE
[BUG] psql: could not connect to server: Host is unreachable

### ISSUE THREAD

**Issue by iot-resister** [maxking/docker-mailman#385]
**Tag/version of Container Images** 0.3

docker logs gives this error for core AND web, using bot mysql and postgres (sqlite never came close) : 

```
psql: could not connect to server: Host is unreachable
        Is the server running on host "172.16.238.10" and accepting
        TCP/IP connections on port 5432?
Postgres is unavailable - sleeping
```

I've exposed the port and changed the IP and manually added the ip

```
  mailman-web:
    image: maxking/postorius:0.3
    container_name: mailman-web
    hostname: mailman-web
    depends_on:
    - database
    links:
    - mailman-core:mailman-core
    - database:database
    volumes:
    - /opt/mailman/web:/opt/mailman-web-data
    environment:
    - DATABASE_TYPE=postgres
    - DATABASE_URL=postgres://mailman:mailmanpass@172.16.238.10:5432/mailmandb
    - HYPERKITTY_API_KEY=someapikey
    - SECRET_KEY=ksjdbaksdba
    - UWSGI_STATIC_MAP=/static=/opt/mailman-web-data/static 
    networks:
      mailman:
        ipv4_address: 172.16.238.11

  database:
    container_name: database
    hostname: postgres
    environment:
      POSTGRES_DB: mailmandb
      POSTGRES_USER: mailman
      POSTGRES_PASSWORD: mailmanpass
    restart: always
    ports:
      - 5432:5432
    image: postgres
    volumes:
    - /opt/mailman/database:/var/lib/postgresql/data
    networks:
      mailman:
        ipv4_address: 172.16.238.10
```
