### ISSUE TITLE
Static assets not served when using external proxy

### ISSUE THREAD

**Issue by gandhiano** [maxking/docker-mailman#45]
When using [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy), the static assets for the web UI are not served. This is due to the assets location not being visible to the nginx container.

The documentation on [setting up the webserver](https://github.com/maxking/docker-mailman#setting-up-your-web-server) could made this explicit.

**Comment by maxking** [comment]
It is possible to just mount `/opt/mailman/web` in the nginx container and serve the static files. 

It will be a good idea to document this somewhere though. 

Thanks!

**Comment by setiseta** [comment]
is it only with proxy?
if I map the port of uwsgi to the host, I still get no static content.
or am I doing something wrong?

**Comment by maxking** [comment]
@setiseta I haven't configured uwsgi to actually serve static files. I am assuming that it will be served directly by the web server to have better performance.

If you really want to, it is technically possible to run the containers with a different command one that will serve the static files too. You will have to edit the docker-compose.yaml file and manually specify that in a `command` under mailman-web configuration. 

Look at [docker-compose reference about command](https://docs.docker.com/compose/compose-file/compose-file-v2/#command) and [uwsgi docs for serving static files](http://uwsgi-docs.readthedocs.io/en/latest/StaticFiles.html?highlight=serving%20static%20files). Note that inside the container, the static files are at `/opt/mailman-web-data/static`

**Comment by setiseta** [comment]
ok, thank you. its for testing at the moment.
it works with your suggested change of the command.
thank you.

**Comment by karsalfrink** [comment]
@gandhiano would you mind sharing your docker-compose file? I am trying to set things up with [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) as well but having little luck…

**Comment by maxking** [comment]
@karsalfrink If you can share your compose file I can have a look and tell you what went wrong.

**Comment by karsalfrink** [comment]
@maxking sure thing, thanks. You'll find it below.

I have successfully set up nginx-proxy with [mattermost-docker](https://github.com/mattermost/mattermost-docker) using [this approach](https://forum.mattermost.org/t/use-nginx-proxy-and-v3-7-1-docker/3062). I am trying to do the same for mailman.

Both mattermost and mailman have cname subdomains pointing to the ip of my vps. Mattermost loads without issue. But when I try to load mailman I get redirected to mattermost. When I shut down the mattermost image mailman doesn't load either, which leads me to believe something isn't right with how I am hooking up mailman to nginx-proxy.

```
version: '2'

services:
  mailman-core:
    image: maxking/mailman-core:0.1
    container_name: mailman-core
    hostname: mailman-core
    volumes:
    - /opt/mailman/core:/opt/mailman/
    links:
    - database:database
    depends_on:
    - database
    environment:
    - DATABASE_URL=postgres://mailman:mailmanpass@database/mailmandb
    - DATABASE_TYPE=postgres
    - DATABASE_CLASS=mailman.database.postgresql.PostgreSQLDatabase
    - HYPERKITTY_API_KEY=besmear-mimicked-bid
    networks:
      mailman:
        ipv4_address: 172.19.199.2

  mailman-web:
    image: maxking/mailman-web:0.1
    container_name: mailman-web
    hostname: mailman-web
    depends_on:
    - database
    links:
    - mailman-core:mailman-core
    - database:database
    volumes:
    - /opt/mailman/web:/opt/mailman-web-data
    environment:
    - SERVE_FROM_DOMAIN=lists.mydomain.com
    - DATABASE_TYPE=postgres
    - DATABASE_URL=postgres://mailman:mailmanpass@database/mailmandb
    - HYPERKITTY_API_KEY=besmear-mimicked-bid
    - MAILMAN_ADMIN_USER=admin
    - MAILMAN_ADMIN_EMAIL=admin@lists.mydomain.com
    - SECRET_KEY=fortuity-eclogue-younker
    - VIRTUAL_HOST=lists.mydomain.com
    - LETSENCRYPT_HOST=lists.mydomain.com
    - LETSENCRYPT_EMAIL=letsencrypt@mydomain.com
    - VIRTUAL_PROTO=uwsgi
    - VIRTUAL_PORT=8080
    expose:
    - "8080"
    - "8000"
    command: --static-map /static=/opt/mailman-web-data/static
    networks:
      mailman:
        ipv4_address: 172.19.199.3

  database:
    environment:
      POSTGRES_DB: mailmandb
      POSTGRES_USER: mailman
      POSTGRES_PASSWORD: mailmanpass
    restart: always
    image: postgres:9.6-alpine
    volumes:
    - /opt/mailman/database:/var/lib/postgresql/data
    networks:
      mailman:
        ipv4_address: 172.19.199.4

networks:
   mailman:
     driver: bridge
     ipam:
       driver: default
       config:
       -
         subnet: 172.19.199.0/24
```
