### ISSUE TITLE
ERROR: Pool overlaps with other one on this address space

### ISSUE THREAD

**Issue by arunodhayam10d** [maxking/docker-mailman#522]
I have tried with docker network prune but after docker-compose up it will show again. It's not worked for me.
I also removed the docker from the instance and again installed it. There is no change.
Also, I restart the docker service. It's Not worked for me.

Please Help me...

**Comment by jasonhildebrand** [comment]
In docker-compose.yaml, go to the bottom where it defines the network.

Remove these lines:
```
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.19.199.0/24
```

leaving just these lines:
```
networks:
  mailman:
```

Doing this allowed me to get past this error and start the containers.  The default docker-compose.yaml file says that the network should use a specific subnet, but this may conflict with other networks which already exist on your server.  It is better to leave it undefined (e.g. remove the above lines) so that docker will choose an available subnet.
