### ISSUE TITLE
[BUG] mailman-web: `EMAIL_USE_TLS/EMAIL_USE_SSL`

### ISSUE THREAD

**Issue by raph-topo** [maxking/docker-mailman#624]
**Tag/version of Container Images**
`latest` as of today ([34b5c3af84cc](https://hub.docker.com/layers/maxking/mailman-core/latest/images/sha256-34b5c3af84cce9b3d3a758e12cb4edeabbc1559b4fba14cb85532471b5a0f199?context=explore))

My mail server does support both SSL/TLS & STARTTLS flawlessly in all sorts of configurations.

### To Reproduce

```yaml
services:
  web:
    image: maxking/mailman-web
    environment:
      - SMTP_HOST=<mail.example.com>
      - SMTP_PORT=465
      - SMTP_HOST_USER=<user>
      - SMTP_HOST_PASSWORD=<pass>
      - SMTP_USE_SSL=True
      - SMTP_USE_TLS=False
```

`$ docker-compose exec mailman-web /opt/mailman-web/manage.py sendtestemail hostmaster@example.com`

**Hangs**. 

```yaml
services:
  web:
    image: maxking/mailman-web
    environment:
      - SMTP_HOST=<mail.example.com>
      - SMTP_PORT=587
      - SMTP_HOST_USER=<user>
      - SMTP_HOST_PASSWORD=<pass>
      - SMTP_USE_TLS=True
      - SMTP_USE_SSL=False
```

`$ docker-compose exec mailman-web /opt/mailman-web/manage.py sendtestemail hostmaster@example.com`

**Works**.

### Logs

I couldn't find any error message in any of the logs in `/opt/mailman-web-data/logs` pertaining to SMTP, as such I have no more information.
