### ISSUE TITLE
SMTP: Connection lost during _handle_client()

### ISSUE THREAD

**Issue by tarneaux** [maxking/docker-mailman#639]
**Tag/version of Container Images**
0.4.*

I am not using the bug template because I believe I made a mistake.

I am trying to get docker-mailman to work with Docker-Mailserver and Caddy.

Below are the relevant parts of my compose file.

All environment variables are of course defined in `.env`.

<details>
<summary>Caddy & networks</summary>

```yaml
networks:
  proxy:
  mailman:

services:
  caddy:
    image: docker.io/library/caddy:alpine
    container_name: caddy
    command: caddy run --config /etc/caddy/Caddyfile
    restart: always
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ${DATA_PATH}/mailman/web/static:/srv/mailman-static
    environment:
      - TZ=Europe/Paris
```
</details>

<details>

<summary>docker-mailserver</summary>

```yaml
  email:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.renn.es
    env_file: email.env
    stop_grace_period: 1m
    restart: always
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 1
    ports:
      - "25:25"   # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ${DATA_PATH}/email/mail-data/:/var/mail/
      - ${DATA_PATH}/email/mail-state/:/var/mail-state/
      - ${DATA_PATH}/email/mail-logs/:/var/log/mail/
      - ${DATA_PATH}/email/config/:/tmp/docker-mailserver/
      - ./email-jail.local:/etc/fail2ban/jail.d/user-jail.local
      - /etc/localtime:/etc/localtime:ro
      - ./mailboxes.conf:/etc/dovecot/conf.d/15-mailboxes.conf:ro
      - ${DATA_PATH}/caddy/data/certificates/acme-v02.api.letsencrypt.org-directory/mail.renn.es/mail.renn.es.crt:/etc/letsencrypt/live/mail.renn.es/fullchain.pem
      - ${DATA_PATH}/caddy/data/certificates/acme-v02.api.letsencrypt.org-directory/mail.renn.es/mail.renn.es.key:/etc/letsencrypt/live/mail.renn.es/privkey.pem
    cap_add:
      - NET_ADMIN
    environment:
      SSL_TYPE: letsencrypt
```
</details>

<details>

<summary>mailman</summary>

```yaml
  mailman-core:
    image: maxking/mailman-core:0.4 # latest is not published
    container_name: mailman-core
    hostname: mailman-core
    volumes:
      - ${DATA_PATH}/mailman/core:/opt/mailman/
    stop_grace_period: 30s
    links:
      - mailman-db:database
    depends_on:
      - mailman-db
    environment:
      DATABASE_URL: postgresql://mailman:${MAILMAN_DB_PW}@database/mailmandb
      DATABASE_TYPE: postgres
      DATABASE_CLASS: mailman.database.postgresql.PostgreSQLDatabase
      HYPERKITTY_API_KEY: ${MAILMAN_API_KEY}
      SMTP_HOST: mail.renn.es
      SMTP_HOST_USER: lists@renn.es
      SMTP_HOST_PASSWORD: ${MAILMAN_EMAIL_PW}
      SMTP_PORT: 587
      MTA: postfix
    networks:
      - mailman

  mailman-web:
    image: maxking/mailman-web:0.4 # latest is not published
    container_name: mailman-web
    hostname: mailman-web
    depends_on:
      - mailman-db
    links:
      - mailman-core:mailman-core
      - mailman-db:database
    volumes:
      - ${DATA_PATH}/mailman/web:/opt/mailman-web-data
    environment:
      DATABASE_TYPE: postgres
      DATABASE_URL: postgresql://mailman:${MAILMAN_DB_PW}@database/mailmandb
      HYPERKITTY_API_KEY: ${MAILMAN_API_KEY}
      SECRET_KEY: ${MAILMAN_SECRET_KEY}
      SERVE_FROM_DOMAIN: lists.renn.es
      MAILMAN_ADMIN_USER: root
      MAILMAN_ADMIN_EMAIL: admin@renn.es
    networks:
      - proxy
      - mailman

  mailman-db:
    image: postgres:11-alpine
    container_name: mailman-db
    environment:
      POSTGRES_DB: mailmandb
      POSTGRES_USER: mailman
      POSTGRES_PASSWORD: ${MAILMAN_DB_PW}
    volumes:
      - ${DATA_PATH}/mailman/db:/var/lib/postgresql/data
    networks:
      - mailman

```
</details>

There is also an email account which has the correct password (set in .env as MAILMAN_EMAIL_PW)

After generating a password and adding it to:
```bash
docker exec -it mailman-web python3 manage.py changepassword
```

Connecting shows the "Verify your e-mail address" page (`/accounts/confirm-email`).

No email comes in, and checking logs gives:
```bash
doas tail -f /data/mailman/core/var/logs/*
```

```
[restart container]
[...]
==> /data/mailman/core/var/logs/smtp.log <==
Jun 30 18:39:58 2023 (26) Available AUTH mechanisms: LOGIN(builtin) PLAIN(builtin)
Jun 30 18:39:58 2023 (26) Peer: ('172.24.0.3', 42356)
Jun 30 18:39:58 2023 (26) ('172.24.0.3', 42356) handling connection
Jun 30 18:39:58 2023 (26) ('172.24.0.3', 42356) EOF received
Jun 30 18:39:58 2023 (26) ('172.24.0.3', 42356) Connection lost during _handle_client()
Jun 30 18:39:58 2023 (26) ('172.24.0.3', 42356) connection lost
[...]
```

EDIT: Using port 25 instead of 587 for SMTP throws the same error.
