### ISSUE TITLE
Error installing mailman3 - failed to create network docker-mailman_mailman

### ISSUE THREAD

**Issue by odhiambo** [maxking/docker-mailman#756]
Hello admins,

I have gotten stuck installing Mailman3 using Docker, to integrate with mailcow-dockernized. I am following three HOWTOS - [0] and [1], comparing the instructions with the ones given at https://asynchronous.in/docker-mailman/, and to be honest, I don't see much difference.

I get the following error:
```
root@srv1:/opt/docker-mailman# docker compose up -d
[+] Running 1/1
 ✘ Network docker-mailman_mailman  Error                                                                                                                                                                             
failed to create network docker-mailman_mailman: Error response from daemon: invalid pool request: Pool overlaps with other one on this address space
```

[0] This guide - https://docs.mailcow.email/third_party/mailman3/third_party-mailman3/.
It says I create /opt/mailcow-dockerized/docker-compose.override.yml containing:
```
services:
  postfix-mailcow:
    volumes:
      - /opt/mailman:/opt/mailman
    networks:
      - docker-mailman_mailman

networks:
  docker-mailman_mailman:
    external: true
```

And the [0] refers to [1] https://github.com/g4rf/dockerized-mailcow-mailman, which also says I create the same file  /opt/mailcow-dockerized/docker-compose.override.yml - but in this case the volume spec is different:
```
services:
  postfix-mailcow:
    volumes:
      - /opt/mailman/core/var/data/:/opt/mailman/core/var/data/
    networks:
      - docker-mailman_mailman

networks:
  docker-mailman_mailman:
    external: true
```

Because I am a n00b with Docker, I am wondering which one is the correct volume spec I should use. Is it "/opt/mailman:/opt/mailman" or the "/opt/mailman/core/var/data/:/opt/mailman/core/var/data/"?

And what might be the cause of the error that I am getting??

Thank you.
